// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://pacific-reef-10230.herokuapp.com/api',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
  ],
  credentialsKey: 'credentials',
  facebook_id: '653371135015179',
  google_id: '841813101724-fbuf95a74j9pqtgoqk3vmbocnocv49ia.apps.googleusercontent.com'
};
